name: Build

# Defines the trigger for this action (e.g. [pull_request, push])
# For more information see: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#about-workflow-events)
on: push

jobs:
  build:
    name: Build and check-style
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go v1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: ^12.18.3

      # Checks out the current repository.
      - uses: actions/checkout@v2

      # This action allows caching dependencies to improve workflow execution time.
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check the code style, run tests, build and bundle the plugin.
        run: make all
        env:
          TERM: dumb

      - name: Prepare artifact metadata
        id: prepare_artifact_metadata
        run: |
          echo ::set-output name=BUNDLE_NAME::mattermost-plugin-$(grep '"'"id"'"\s*:\s*"' plugin.json | head -1 | cut -d'"' -f4)-v$(grep '"'"version"'"\s*:\s*"' plugin.json | head -1 | cut -d'"' -f4).tar.gz

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.prepare_artifact_metadata.outputs.BUNDLE_NAME }}
          path: dist/${{ steps.prepare_artifact_metadata.outputs.BUNDLE_NAME }}
